highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: paulwalko.github.io
devurl: paulwalko.github.io
name: Paul Walko
title: Paul Walko
description: "Paul Walko's personal website"

my:
    displayName: Paul Walko
    realName: Paul Walko
    jobTitle: "Student at Virgina Tech"
    contact:
        email: paulsw.pw@gmail.com
        github: https://www.github.com/paulwalko
        google-plus: http://www.google.com/+paulwalko
        address:
            country: United States
    skills:
        security: ["Wireshark", "IDA", "Ollydebug"]
        coding: ["C", "C++", "Python", "Java", "bash", "HTML"]
        tools: ["Linux"]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
