highlighter: rouge


gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
#permalink: /:categories/:title
permalink: pretty
excerpt_separator: "[-----]"

#mode: dev
mode: product
url: https://paul.walko.org/
enforce_ssl: paul.walko.org/
devurl: http://localhost:4000/
name: Paul Walko
title: Paul Walko
description: "Paul Walko's personal website"

my:
    displayName: Paul Walko
    realName: Paul Walko
    jobTitle: "Student at Virgina Tech"
    contact:
        email: paulsw.pw@gmail.com
        github: https://www.github.com/paulwalko
        google-plus: http://www.google.com/+paulwalko
        address:
            country: United States
    skills:
        security: ["Wireshark", "IDA", "GDB"]
        coding: ["C", "C++", "Python", "Java", "bash", "HTML"]
        tools: ["Linux", "vim", "Arch Linux"]

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
    values:
        layout: markdownreader_bare
